global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mongodb-atlas-backup'
    metrics_path: /probe
    params:
      module: [mongodb_atlas_backup]
      target: ['http://mockserver/mongodb_backup.json']
    static_configs:
      - targets: ['json-exporter:7979']